target-version = "py313"
line-length = 100

[lint]
preview = true
select = ["ALL"]
ignore = [
    "blind-except", # Do not catch blind exception: Exception
    "missing-copyright-notice",
    "incorrect-blank-line-before-class", # Require blank line after class declaration before docstring
    "multi-line-summary-first-line", # Start multiline docstring on same line as triple-quote
    "DTZ", # datetime without timezone
    "missing-whitespace-around-arithmetic-operator",
    "raw-string-in-exception",
    "f-string-in-exception",
    "unsorted-imports",
    "implicit-namespace-package", # File is part of an implicit namespace package. Add an `__init__.py`.
    "invalid-class-name", # Class name should be CapWords
    "too-many-public-methods",
    "too-many-return-statements",
    "too-many-arguments",
    "too-many-locals",
    "too-many-statements",
    "too-many-positional-arguments",
    "literal-membership", # Use a set literal when testing for membership
    "too-many-statements-in-try-clause",
    "pytest-unittest-assertion",
    "pytest-unittest-raises-assertion",
    "superfluous-else-return",
    "superfluous-else-raise",
    "superfluous-else-continue",
    "suspicious-non-cryptographic-random-usage",
    "print",
    "typing-only-standard-library-import",
    "runtime-cast-value", # Add quotes to type expression in typing.cast()
    "raise-vanilla-args", # No string arguments in custom exceptions
    "try-consider-else", # Move return to else block
    "error-instead-of-exception", # logger.exception() instead of logger.error()
    "outdated-version-block", # Version block is outdated for minimum Python version
]

[lint.mccabe]
max-complexity = 10

[lint.pydocstyle]
convention = "google"
